package durablestate

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// TestCanonicalJSON_ByteParityWithPythonReference locks canonicalJSONBytes'
// output (and therefore canonicalHash's sha256) to bytes independently
// computed with the pinned reference's own serialization convention:
//
//	python3 -c "import json; print(json.dumps(obj, sort_keys=True, separators=(',', ':')))"
//
// with Python's default ensure_ascii=True. This is the adversarial
// regression for the Review-blocking defect where Go's encoding/json
// HTML-escapes '<', '>', and '&' (which Python never escapes) and leaves
// non-ASCII runes as raw UTF-8 (which Python's ensure_ascii=True instead
// \u-escapes). Every case below was generated by running the exact Python
// one-liner above against CPython 3, not guessed.
func TestCanonicalJSON_ByteParityWithPythonReference(t *testing.T) {
	cases := []struct {
		name        string
		body        map[string]any
		wantJSON    string
		wantSHA256  string
		wantByteLen int
	}{
		{
			name:        "angle_brackets_and_ampersand_not_escaped",
			body:        map[string]any{"text": "a<b&c>"},
			wantJSON:    `{"text":"a<b&c>"}`,
			wantSHA256:  "599bde0ace337ee1f6cab10916beb9473694eee8da616cbbd94ee3e7e5c89dd7",
			wantByteLen: 17,
		},
		{
			name:        "quote_and_backslash_escaped",
			body:        map[string]any{"text": "quote\"back\\slash"},
			wantJSON:    `{"text":"quote\"back\\slash"}`,
			wantSHA256:  "f7e6424d256f4ed556fc82d753dffb39cb74033ef3d8521750a64d0c5ab827e6",
			wantByteLen: 29,
		},
		{
			name:        "control_chars_including_DEL_escaped",
			body:        map[string]any{"text": "control\x01\x1f\x7f"},
			wantJSON:    `{"text":"control\u0001\u001f\u007f"}`,
			wantSHA256:  "046829a5feadcd841e4f8088170712aef27ac153d7eb6e2c533cc6540ee1c4b6",
			wantByteLen: 36,
		},
		{
			name:        "non_ascii_BMP_escaped_to_uXXXX",
			body:        map[string]any{"text": "unicode\u00e9\u20ac"},
			wantJSON:    `{"text":"unicode\u00e9\u20ac"}`,
			wantSHA256:  "9a98f657db3730269f3d54faa08545504189920d0adc2d0b20e726e8039f2eab",
			wantByteLen: 30,
		},
		{
			name:        "astral_char_escaped_as_surrogate_pair",
			body:        map[string]any{"text": "emoji\U0001F600"},
			wantJSON:    `{"text":"emoji\ud83d\ude00"}`,
			wantSHA256:  "d78bb4ad129c47a0e8ebadc23f877c2734a610794e9b511485890e4737be635b",
			wantByteLen: 28,
		},
		{
			name:        "keys_sorted_recursively",
			body:        map[string]any{"z": float64(1), "a": float64(2), "m": map[string]any{"y": float64(1), "b": float64(2)}},
			wantJSON:    `{"a":2,"m":{"b":2,"y":1},"z":1}`,
			wantSHA256:  "dcf263fcb20d6d93e196e2ec9816c26fa0790d199080d1b101f2b31ced46ecc1",
			wantByteLen: 31,
		},
		{
			name:        "list_with_mixed_types_and_html_sensitive_strings",
			body:        map[string]any{"list": []any{"<x>", "&amp;", float64(3), nil, true, false}},
			wantJSON:    `{"list":["<x>","&amp;",3,null,true,false]}`,
			wantSHA256:  "1fa11637ae019f349daa545494fd25a23a923b44f0db6db99259fe42aee8220d",
			wantByteLen: 42,
		},
		{
			name:        "empty_object_and_array",
			body:        map[string]any{"empty": map[string]any{}, "arr": []any{}},
			wantJSON:    `{"arr":[],"empty":{}}`,
			wantSHA256:  "14f150181fba818f80385c8fe376faa6c6bd5c588c9efdb764f514c8a58826f2",
			wantByteLen: 21,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			encoded, err := canonicalJSONBytes(tc.body)
			require.NoError(t, err)
			require.Equal(t, tc.wantJSON, string(encoded), "canonical JSON bytes must match Python's json.dumps output exactly")
			require.Len(t, encoded, tc.wantByteLen)

			sha, err := canonicalHash(tc.body)
			require.NoError(t, err)
			require.Equal(t, tc.wantSHA256, sha, "sha256 must match the pinned Python reference's canonical_hash")

			n, err := byteCountOf(tc.body)
			require.NoError(t, err)
			require.Equal(t, tc.wantByteLen, n)
		})
	}
}

// TestCanonicalJSON_DoesNotHTMLEscape is the review's exact minimal repro:
// a body containing '<', '>', and '&' must hash identically to what the
// pinned Python reference computes, not to Go's HTML-escaped encoding/json
// output.
func TestCanonicalJSON_DoesNotHTMLEscape(t *testing.T) {
	body := map[string]any{"text": "a<b&c>"}
	sha, err := canonicalHash(body)
	require.NoError(t, err)
	require.Equal(t, "599bde0ace337ee1f6cab10916beb9473694eee8da616cbbd94ee3e7e5c89dd7", sha)
	// The HTML-escaped (buggy) Go json.Marshal encoding would instead hash
	// to 84e85d33...; assert we are NOT producing that.
	require.NotEqual(t, "84e85d33", sha[:8])
}

// TestCanonicalJSON_RecordIDSetSHA256Unaffected documents that
// record_id_set_sha256 (record IDs joined by newline, not JSON-encoded) is
// untouched by this fix — it never went through JSON string escaping.
func TestCanonicalJSON_RecordIDSetSHA256Unaffected(t *testing.T) {
	got := recordIDSetSHA256([]string{"b<b>", "a&a"})
	// sha256("a&a\nb<b>") — sorted, newline-joined, no JSON escaping at all.
	require.Len(t, got, 64)
}
